### ISSUE TITLE
ERROR creación de proyectos 

### ISSUE THREAD

**Issue by MacaA2000** [liceo-social/liceo#48]
![image](https://user-images.githubusercontent.com/79325214/108530354-cdb93680-72d5-11eb-9780-4eab49bc05d0.png)

Me he lanzado a crear proyectos... me ha dejado crear dos, me sale esto en la pantallla...
Si me pongo a crear una persona nueva, pincho en proyectos y me salen los dos creados...

Donde toco la lio.....

**Comment by mariogarcia** [comment]
Le hecho un vistazo y te digo algo asap

**Comment by mariogarcia** [comment]
@joseanrey puedes acceder a los logs del servidor ? Probablemente nos de mas informacion sobre el problema

**Comment by mariogarcia** [comment]
@MacaA2000 por cierto no te preocupes, el que no hace nada no rompe nada, ademas probablemente sea algo que no hemos tenido en cuenta y todo esto es para que el sistema sea mejor :+1:

**Comment by joseanrey** [comment]
Hola! Perdonad que no he sacado hueco hasta ahora, @mariogarcia te pego el log, entiendo que el error puede ser este al listar el listado de proyectos:

manager_1  | 2021-02-25 19:13:05.932 ERROR --- [nio-8080-exec-7] .a.c.c.C.[.[.[.[grailsDispatcherServlet] : Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.grails.gsp.GroovyPagesException: Error processing GroovyPageView: [views/project/index.gsp:39] Error executing tag <f:table>: [views/templates/_fields/_table.gsp:21] Error executing tag <f:display>: Cannot invoke method size() on null object] with root cause

Hay más pero son todos el mismo, si necesitas más detalles me dices

**Comment by mariogarcia** [comment]
Vale pues le echo un vistazo, parece claramente un error de la aplicacion. Probablemente habra que sacar una nueva version. Os aviso @MacaA2000 @joseanrey en cuanto lo tenga.
